# Generated by Django 3.0.4 on 2020-03-10 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='title',
            new_name='name',
        ),
    ]
